<?php

/**
 * Implements hook_install().
 */
function gsb_feature_video_install() {
  // Make the weight of our module one higher than panopoly_widgets.
  $weight = db_select('system', 's')
              ->fields('s', array('weight'))
              ->condition('name', 'panopoly_widgets', '=')
              ->execute()
              ->fetchField();

  db_update('system')
    ->fields(array('weight' => $weight +1))
    ->condition('name', 'gsb_feature_video', '=')
    ->execute();
}