<?php
/**
 * @file
 * Code for the GSB Feature Video feature.
 */
 

/**
 * Implements hook_entity_info_alter().
 *
 * Here we tell Drupal about our custom fpp -
 * 'video'.
 *
 */
 function gsb_feature_video_entity_info_alter(&$entity_info) {

  // create the GSB Video FPP

  $entity_info['fieldable_panels_pane']['bundles']['video'] = array(
    'label' => t('Add GSB video'),
    'pane category' => t('GSB Video FPP'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_text.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/video',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );

}

/**
 * Implements hook_form_alter()
 */
function gsb_feature_video_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form' && $form['#bundle'] == 'video') {
      $language = $form['field_video_description']['#language'];
      $form['field_video_description'][$language][0]['value']['#maxlength'] = '150';
      $form['field_video_description'][$language][0]['value']['#description'] = t('Limited to 150 characters');
  }

}


