<?php
/**
 * @file
 * Code for the GSB Feature Video feature.
 */

include_once 'gsb_feature_video.features.inc';
/**
 * @file
 * Code for the GSB Feature Video feature.
 */


/**
 * Implements hook_entity_info_alter().
 *
 * Here we tell Drupal about our custom fpp -
 * 'video'.
 *
 */
 function gsb_feature_video_entity_info_alter(&$entity_info) {

  // create the GSB Video FPP

  $entity_info['fieldable_panels_pane']['bundles']['video'] = array(
    'label' => t('Video'),
    'pane category' => t('GSB panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_text.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/video',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );

}
